### ISSUE TITLE
Create dashboard for tracking hub status

### ISSUE THREAD

**Issue by mellybelly** [National-COVID-Cohort-Collaborative/operations#1]
This is needed urgently

we need a way to track who has engaged with which hubs
main contact, regulatory contact, data ingest contact
status of IRB, DUA 
status of data ingest
update frequency
etc.

@empfff please comment

**Comment by empfff** [comment]
Yes, if this is created, I can fill in which sites have filled in the survey, along with their answers.

**Comment by mellybelly** [comment]
I'm going to assign this to @monicacecilia but please feel free to re-assign.

**Comment by waldenan** [comment]
we have created a draft here 

[HubStatus](https://docs.google.com/spreadsheets/d/1btafAid_yWUbO6gsZzWOSVRtuipuiQRzmsMxLMJzyhw/edit#gid=0)

**Comment by waldenan** [comment]
@empfff will you please check to determine if there is anything else needed on the spreadsheet. Thanks!

**Comment by mellybelly** [comment]
lets reconcile with this [spreadsheet](https://docs.google.com/spreadsheets/d/1UqhIeuUfjqw7hRLo3cIj7G6zlR35j0ToSoQCL92dZlQ/edit#gid=1307066249) 

we should have one source of truth.

**Comment by monicacecilia** [comment]
@mellybelly, @empfff - when I created the spreadsheet (Hub Status), I added some comments to the columns, in the hopes that those would be come options in a drop/down menu. 
I'll implement and see if you like.
Please also comment on whether we are missing any options.

**Comment by empfff** [comment]
Do you want me to add columns to collect the responses from the site survey? Also, do you want me to go ahead and add in responses and sites from the site survey? We are up to 30 responses.

**Comment by monicacecilia** [comment]
Dear Emily, 
- Are the responses from the form (N3C survey) meant to be seen by the public filling up the information on the Hub Status? 
- If sites themselves are adding details here, do we also want them to be able to see the responses?

**Comment by empfff** [comment]
Oh I wasn't aware this spreadsheet was for sites to fill in themselves, I thought it was internal. If it's public, then I think we just need two more columns to show whether the site has filled out the site survey (yes/no) and what data model they're planning on using (OMOP, ACT, PCORnet, TriNetX).

I will make another spreadsheet with the detailed results of the site survey, and will share that internally until we decide what answers we want to make public.

**Comment by mellybelly** [comment]
I think this should be an internal spreadsheet for the admin+leadership team to track sites info- it would be inappropriate to make the contacts etc public. 

The survey results from the form are also private, but you should already have a spreadsheet with those results in the admin folder shared with you. @empfff

**Comment by mellybelly** [comment]
@empfff here are the [results of the survey](https://docs.google.com/spreadsheets/d/1-XwGt7FuV7TFMTWWP22KfdxuRuzIhx5ZId7OJI92ZNE/edit?usp=drive_web&ouid=118411087353017416228) (in admin folder)

**Comment by monicacecilia** [comment]
> lets reconcile with this [spreadsheet](https://docs.google.com/spreadsheets/d/1UqhIeuUfjqw7hRLo3cIj7G6zlR35j0ToSoQCL92dZlQ/edit#gid=1307066249)
> we should have one source of truth.

@mellybelly, @empfff : 
- I updated the 'Hub Status Dashboard' spreadsheet to include all institutions listed in the 'Data Partner List' spreadsheet.
  - There were fields and information added to the 'data partner lists' which did not make much sense without further explanation. I preserved those fields in 5 columns marked as '_Imported from 'Data Partner List_' spreadsheet.'
- All institutions are now listed alphabetically.
- Melissa asked me to remove the 'Data Partner' one afterwards, but I have not yet done so, in the event that Emily or others needs to do anything else with it. I did add a request to please stop populating the spreadsheet. Please feel free to remove editing access or delete the now deprecated list altogether.

**Comment by empfff** [comment]
There are several duplicates in the new spreadsheet. I don't want to delete any because I'm unsure which is the "right" version of each row. (Ex: there are two UNCs, one of which says we're in region "Vanderbilt"?)

I added a new column for Site Survey complete (Y/N), but I'm wait until the dupes are removed to keep entering data.

**Comment by monicacecilia** [comment]
Dear @empfff, 
- The "regions" column come from the 'Data Partners List.' Any possible errors in assignment were propagated from that spreadsheet. I did not want to lose any of the data on the 'Data Partners List,' so I ported over ALL of it. My assumption is that the 'Hub Status' spreadsheet will become 'source of truth' and that Melissa and you may be able to remove / edit redundancy and errors as appropriate in one single place, instead of two.
- For instance, 
  - One of you may assess whether it is necessary and useful to divide the Universities into "regions" (they are simply labeled as "CC" on the 'Data Partners List'
  - If needed, then if UNC is in the wrong "region," we can remove the label. Or create a new region. 
- Great column to add! :bowtie: I updated it to use Data Validation with a drop-down menu (Yes/No).

**Comment by monicacecilia** [comment]
Update: 🌻 
- There are only 4 marked duplicate pairs, marked as [DUPE] and highlighted in yellow. 
- @mellybelly @empfff please review and disambiguate.
