### ISSUE TITLE
strategy for task team literature collection

### ISSUE THREAD

**Issue by mellybelly** [National-COVID-Cohort-Collaborative/operations#121]
A lot of the task teams are collecting literature, we need a strategy for facilitating their sharing and inventorying across N3C. @jmcmurry @andrewjneumann perhaps you can come up with something? Paperpile collection?

**Comment by jmcmurry** [comment]
Easiest is a paperpile collection; however, since not everyone will have a license, we need a way to submit a paper by other mechanism, perhaps via gForm. All we would need is the DOI. Is it just a list you need or some organization too? If so, what are the appropriate 'bins'?

**Comment by jmcmurry** [comment]
I propose we have a trusted set of curators and a generic form for anyone (license or no) to add a suggestion.

OK Paperpile collection (currently blank) is now at http://bit.ly/n3c-paperpile-collection
Form to submit something new to paperpile collection is here: http://bit.ly/n3c-paperpile-submission

@mellybelly please advise.

**Comment by jmcmurry** [comment]
Parking this here for exploration. It is not as feature rich but it is perhaps better than alternative in just this instance? [GSuite rolls its own reference manager.](https://support.google.com/docs/answer/10090962)

**Comment by jmcmurry** [comment]
@deacyma I need full admin access to all of the literature folders in N3C, eg [these](https://drive.google.com/drive/u/0/search?q=title:literature%20type:folder%20in:0ACAAZGaoNkfUUk9PVA). However, because this list is dynamic it would really be best to have it for the [whole parent drive](https://drive.google.com/drive/u/0/folders/0ACAAZGaoNkfUUk9PVA). Please grant it to mcmurryj ... oregonstate dot edu thanks.

**Comment by deacyma** [comment]
@jmcmurry I have upgraded your access to manager. Could you please let me know if this resolved the issue?
