### ISSUE TITLE
Update the Checklist

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#123]
People want to know who to send the DUA to. Can we add Ncats Email DUA submission email to Registration checklist.  

We may need to expand the checklist to include the DUA process 

Let's create a new draft to collect comments and revisions for the next release of the checklist.

**Comment by amvolz** [comment]
@waldenan I have made the requested addition. 

FYI: The checklist is still under review with NCATS on the FAQ draft (was never officially approved.) Any changes I make on the website I simultaneously make on the review draft. (The checklists are currently synchronized in both places including new edits made by NCATS.)

One-by-one as FAQs are approved, they are being removed from the FAQ draft and published on their respective websites. Eventually, the Checklist can exist alone on the draft document. 

All new N3C website FAQs will be created as GitHub tickets, per Melissa's wishes. (NCATS will probably have another mechanism for creating their website's FAQs, since they don't use GitHub.)

**Comment by amvolz** [comment]
The checklist has been updated with all comments above as well as NCATS comments. 

Disregard process stated above for checklist. A new [document dedicated to the CHECKLIST](https://docs.google.com/document/d/197oo1DBNu2bhTXdVvkvErzRcsMWqvdi36TsxVAT0VzM/edit) alone has been created and can be used as new revisions are needed to post to the [Registration Checklist website page](https://covid.cd2h.org/Enclave_Registration_Checklist).
