### ISSUE TITLE
add github members to the org

### ISSUE THREAD

**Issue by mellybelly** [National-COVID-Cohort-Collaborative/operations#28]
e.g. I could not find @jmcmurry in the data governance repo

**Comment by andrewjneumann** [comment]
@jmcmurry is here unless joined after this was created. I need owner access to org to be able to add people. I understand this is already in process and happy to help.

<img width="1029" alt="Screen Shot 2020-06-10 at 6 54 27 PM" src="https://user-images.githubusercontent.com/38451425/84336453-1e27a400-ab4c-11ea-9cd7-ea91c021d839.png">

**Comment by mellybelly** [comment]
you have the power!

**Comment by mellybelly** [comment]
and julie is there now too

**Comment by andrewjneumann** [comment]
@jmcmurry is this https://developer.github.com/v3/orgs/members/#set-organization-membership-for-a-user something we're able to add to your google script?

**Comment by cgcook** [comment]
I've added everyone who's onboarded since N3C's inception and provided a github handle.  

The onboarding form asks but does not require a GitHub handle.  The onboarding description for the GitHub question reads:
_We use Github for issue tracking and management. You can get one free from GitHub.com if you do not already have one. You will be able to view issues without a handle, however, you will not be able to log issues without a handle._

I'm operating on the assumption that if they did not provide a GH handle, we will not add/invite them to the Org.

**Comment by cgcook** [comment]
FYI, there are 45 pending invites as of now (6.12.2020 1:46pm PT).
