### ISSUE TITLE
Registration / Onboarding: Track all requirements here

### ISSUE THREAD

**Issue by cgcook** [National-COVID-Cohort-Collaborative/operations#32]
Centrally tracing requirements in this ticket; add/merge all requirements to this ticket.

- [ ] Overall list of participants
- [ ] Participant list of each workstream and subgroup
- [ ] self serve listservs/google groups
- [ ] Communication: meetings
- [ ] Drive access
- [ ] Individual contact info for communication (may be separate from drive access)
- [ ] Asst contact info for scheduling
- [ ] Institutional/organizational affiliation (Company, University, Medical Ctr...)
- [ ] create Slack channels
- [ ] self serve slack
- [ ] Slack address if different from main email
- [ ] GitHub handle and Name
- [ ] Website stats: people, institutions
- [ ] Removing individuals from a group
- [ ] Team members can find other team members
- [ ] Team members can find other team members contact
- [ ] Collect info re: organizational for Data Use Access
- [ ] Sites sending data -> should sites onboard (not for personal onboarding)
- [ ] change contact information
- [ ] Therapeutic area for clinicians
- [ ] Role/Expertise (match making activities) OR Linkedin ID
- [ ] ORCID iD
- [ ] Twitter handle
- [ ] headshot

**Comment by cgcook** [comment]
For Hub tracking:

- [ ] Institutional key (FWA or ROR)

considerations:
citizen scientists
Pharma

**Comment by cgcook** [comment]
For federated login:

- [ ] institutional email

**Comment by waldenan** [comment]
**Additional Requirements for those who want Access to the Data Only.**
It was suggested/question between the Gov and Harmonization groups if those who want only to access the data that they also need to onboard, create an account or profile.

If they want to use the data they have to provide the following information: This may be a combination of CD2H-N3C onboarding or registration through NCATS for DUR
User profile will include:

Name:
Phone/Email: The email account should be given by the researcher's organization. Commercial email accounts (gmail.com, etc.) are not allowed.
Address
Organization Name*:
ORCID*: (Must be Public)
Confirm completion of training in human subject protection

specs to be considered.

ref.June 3 Email between Davera and Christine

**Comment by mellybelly** [comment]
If they are not required to onboard to get in, we will have to have a synch mechanism to onboard them, which is more prone to breakage. It was decided that it is a requirement to be onboarded. @nqureshi maybe you have ideas how this should work.

**Comment by cgcook** [comment]
[Onboarding: Needs and stakeholders ](https://docs.google.com/spreadsheets/d/1DYWLkTRTHzYJvHyr7qmRg61IXzWg576qrkX3cVpj80E/edit#gid=0)

**Comment by jmcmurry** [comment]
Just an update that I discovered quite accidentally in google groups an undocumented (and potentially new? accidentally exposed?) way to programmatically pull all of the members (not just the GSuite ones). I spoke with @eichmann today about it and he is on the job to:

- pull all of the membership from these CSVs
- pull all the slack membership info
- join the tables and feed the result back to a gSheet on a regular cycle. 

Yayy!!! 

This obviously won't address the white glove scenario (where someone refuses to join the group, but is nevertheless participating in meetings), but it will make it that much easier to handle just those edge cases.

Once we actually have an updated onboard form, stragglers who haven't onboarded yet can be prompted. I'm reluctant to do this until we are really ready. Otherwise people will need to update a prior response which is never optimal.

**Comment by cgcook** [comment]
[slides/notes/diagrams from related meetings](https://docs.google.com/presentation/d/14ZFzZJClSm_F-JLIsuE6vDPuBn6qxMVBvKwy76OR2bM/edit#slide=id.g8b7a7d5912_0_0)

**Comment by cgcook** [comment]
new registration form is live; closing this ticket.
