### ISSUE TITLE
Schedule onboarding calls

### ISSUE THREAD

**Issue by mellybelly** [National-COVID-Cohort-Collaborative/operations#5]
can be done either ad hoc or during weekly phenotype and governance meetings. But generally need a place to have new sites ask questions that is pre-announced.

**Comment by cgcook** [comment]
Melissa, I'm not completely sure I understand this request.  Can you provide the details, or can we discuss?  Thanks.

**Comment by mellybelly** [comment]
Hi Connor, we had discussed the idea of using the governance and/or phenotype calls as venues to help hubs w onboarding rather than holding separate calls. I am not sure if we are far enough along yet to be able to do this, but with the DTA ready and the phenotype ready, perhaps we could take 15 mins each week as a standing agenda item to answer hub questions? or do we need to schedule one off calls? @empfff @waldenan what do you think?

**Comment by empfff** [comment]
I think it would be good to schedule specific onboarding calls rather than squeezing them into existing call agendas. That said, I don't necessarily think it needs to be 1-on-1--we could have onboarding calls with multiple sites at once. Maybe schedule an onboarding call once a week and bill it as "office hours," where any site that needs to onboard can show up?

**Comment by cgcook** [comment]
Hi all.  Following up to clarify/confirm if this is still needed, or if the Phenotype office hours have satisfied this request?

**Comment by empfff** [comment]
Yes I think you can close.

**Comment by cgcook** [comment]
Thanks Emily.
