### ISSUE TITLE
[Enclave] New Home page- difficult to read text...didn’t adjust: minor

### ISSUE THREAD

**Issue by cgcook** [National-COVID-Cohort-Collaborative/operations#65]
Text/elements on homepages didn't correctly dynamically adjust (CSS?).

**Comment by ychae** [comment]
The errors that @waldenan was seeing have been resolved. However, we're still seeing some text overlap on some of the pages that resolve once you refresh the page. 

Is this error still considered catastrophic?

**Comment by waldenan** [comment]
No it isn't I would suggest downgrading it to Minor and we should focus on higher priority items and revisit this later. Thank you for working on it. :-)

**Comment by oneilsh** [comment]
@cgcook @andrewjneumann any objection to adding tags to distinguish issues related to enclave-homepage, dur form, etc?

**Comment by cgcook** [comment]
@oneilsh no objections to adding additional labels.

**Comment by ychae** [comment]
Downgraded to minor as the most problematic issue has been resolved. Keeping open to make sure we address the lesser issue of the text not being reactive when going from a very large window to a small window (and vice versa) without having to refresh the page. 

To repro:
1. Go to enclave homepage (I used Chrome Version 84.0.4147.105 (Official Build) (64-bit))
2. Make the window large, text will tend to justify to top, rather than center
3. Refresh the page, text will justify to center as expected

There's another issue where (when the window is particularly small) the text squishes out of their "boxes", such as the "Step 1, Step 2" section on the landing page and the Training boxes on the Training tab. I'm not sure if this is a separate issue and needs a new ticket to track.

**Comment by cgcook** [comment]
Hi @ychae and @oneilsh - checking on this issue.  Have the outstanding minor issues been resolved?  Thanks for providing an update or closing the ticket if appropriate.

**Comment by ychae** [comment]
@cgcook Most of the issues have been resolved as long as people don't try to make the screen very narrow or view it on mobile. @oneilsh should we close this ticket and reopen if we get a bunch of issues filed about it?

**Comment by cgcook** [comment]
thanks @ychae; I'm going to suggest we close this ticket and (re)open a new one if needed.
